-- Agent Wallet production schema draft.
-- Target database: Postgres 15+.
-- UUIDs are generated by the app today; production can switch to gen_random_uuid().

create extension if not exists pgcrypto;

create table if not exists app_users (
  id text primary key,
  privy_user_id text unique,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists agents (
  id uuid primary key,
  owner_user_id text not null references app_users(id),
  name text not null,
  status text not null check (status in ('active', 'paused', 'revoked')),
  strategy_profile text not null,
  execution_mode text not null check (execution_mode in ('observe_only', 'simulate', 'mainnet_small')),
  user_wallet_address text,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists agent_vaults (
  agent_id uuid primary key references agents(id) on delete cascade,
  chain_id integer not null default 196,
  chain_name text not null default 'X Layer',
  address text not null,
  display_address text not null,
  wallet_type text not null,
  balance_snapshot_okb numeric(38, 18) not null default 0,
  last_balance_sync_at timestamptz not null
);

create table if not exists agent_policies (
  agent_id uuid primary key references agents(id) on delete cascade,
  max_single_spend_okb numeric(38, 18) not null,
  daily_budget_okb numeric(38, 18) not null,
  daily_loss_limit_okb numeric(38, 18) not null,
  allowed_markets text[] not null,
  allowed_tokens text[] not null,
  expires_at timestamptz not null,
  revoked boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists agent_memories (
  agent_id uuid primary key references agents(id) on delete cascade,
  user_preferences jsonb not null default '[]'::jsonb,
  risk_profile jsonb not null default '{}'::jsonb,
  strategy_hints jsonb not null default '[]'::jsonb,
  recent_lessons jsonb not null default '[]'::jsonb,
  counters jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null
);

create table if not exists agent_messages (
  id uuid primary key,
  agent_id uuid not null references agents(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'tool')),
  content text not null,
  action text,
  decision jsonb,
  tool_result jsonb,
  created_at timestamptz not null
);

create index if not exists agent_messages_agent_created_idx on agent_messages(agent_id, created_at desc);

create table if not exists agent_runs (
  id uuid primary key,
  agent_id uuid not null references agents(id) on delete cascade,
  status text not null check (status in ('completed', 'blocked', 'failed')),
  goal text not null,
  router jsonb not null,
  observed_market_count integer not null,
  selected_market_id text,
  selected_question text,
  selection_reason text not null,
  intent_id uuid,
  preview_id uuid,
  risk_notes jsonb not null default '[]'::jsonb,
  created_at timestamptz not null
);

create index if not exists agent_runs_agent_created_idx on agent_runs(agent_id, created_at desc);

create table if not exists trade_intents (
  id uuid primary key,
  agent_id uuid not null references agents(id) on delete cascade,
  market text not null,
  market_source text not null,
  side text not null,
  amount_okb numeric(38, 18) not null,
  confidence numeric(8, 6) not null,
  expected_probability numeric(8, 6) not null,
  market_probability numeric(8, 6),
  external_market_id text,
  external_market_slug text,
  external_question text,
  plugin_name text,
  tool_route jsonb,
  execution_plan jsonb,
  live_mode_required boolean,
  preview_required boolean,
  reasoning text not null,
  status text not null,
  risk_notes jsonb not null default '[]'::jsonb,
  created_at timestamptz not null
);

create index if not exists trade_intents_agent_created_idx on trade_intents(agent_id, created_at desc);

create table if not exists execution_previews (
  id uuid primary key,
  agent_id uuid not null references agents(id) on delete cascade,
  intent_id uuid not null references trade_intents(id) on delete cascade,
  provider text not null,
  mode text not null check (mode in ('paper', 'live')),
  market text not null,
  side text not null,
  amount_okb numeric(38, 18) not null,
  estimated_cost_okb numeric(38, 18) not null,
  estimated_gas_okb numeric(38, 18) not null,
  price numeric(8, 6),
  tool_route jsonb,
  warnings jsonb not null default '[]'::jsonb,
  safety_summary jsonb not null default '{}'::jsonb,
  confirmation_text text,
  confirmation_code text,
  confirmation_status text not null,
  confirmation_attempts integer not null default 0,
  max_confirmation_attempts integer not null default 5,
  confirmed_at timestamptz,
  confirmed_by text,
  expires_at timestamptz not null,
  created_at timestamptz not null
);

create index if not exists execution_previews_agent_created_idx on execution_previews(agent_id, created_at desc);
create index if not exists execution_previews_intent_fresh_idx on execution_previews(intent_id, expires_at desc);

create table if not exists execution_records (
  id uuid primary key,
  agent_id uuid not null references agents(id) on delete cascade,
  intent_id uuid not null references trade_intents(id) on delete cascade,
  status text not null check (status in ('simulated', 'executed', 'blocked', 'failed')),
  tx_hash text,
  cost_okb numeric(38, 18) not null default 0,
  error text,
  explorer_url text,
  provider text,
  created_at timestamptz not null
);

create index if not exists execution_records_agent_created_idx on execution_records(agent_id, created_at desc);

create table if not exists audit_events (
  id uuid primary key,
  agent_id uuid not null references agents(id) on delete cascade,
  type text not null,
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null
);

create index if not exists audit_events_agent_created_idx on audit_events(agent_id, created_at desc);

create table if not exists training_exports (
  id uuid primary key,
  agent_id uuid references agents(id) on delete set null,
  storage_url text not null,
  format text not null default 'jsonl',
  example_count integer not null,
  created_at timestamptz not null default now()
);

-- V2 / HWallet production data layer.
-- These tables replace local `.agent-wallet-data/*.jsonl` for multi-user App traffic.
-- They are user-scoped by design so wallet records, memory, audit, and actions never bleed across users.

create table if not exists hwallet_wallets (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references app_users(id) on delete cascade,
  address text not null,
  chain_id integer not null default 196 check (chain_id = 196),
  network text not null default 'X Layer',
  status text not null default 'ready' check (status in ('ready', 'pending', 'revoked')),
  source text not null default 'privy_embedded_wallet',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, chain_id)
);

create index if not exists hwallet_wallets_user_idx on hwallet_wallets(user_id);
create index if not exists hwallet_wallets_address_idx on hwallet_wallets(lower(address));

create table if not exists hwallet_wallet_assets (
  id uuid primary key default gen_random_uuid(),
  wallet_id uuid not null references hwallet_wallets(id) on delete cascade,
  user_id text not null references app_users(id) on delete cascade,
  symbol text not null check (symbol in ('USDT0', 'USDT', 'OKB')),
  name text not null,
  amount numeric(38, 18) not null default 0,
  amount_label text not null default '0',
  value_label text not null default '-',
  sync_status text not null check (sync_status in ('pending', 'synced', 'failed')),
  raw_json jsonb not null default '{}'::jsonb,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (wallet_id, symbol)
);

create index if not exists hwallet_wallet_assets_user_idx on hwallet_wallet_assets(user_id);
create index if not exists hwallet_wallet_assets_wallet_idx on hwallet_wallet_assets(wallet_id);

create table if not exists hwallet_wallet_transfers (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references app_users(id) on delete cascade,
  wallet_id uuid not null references hwallet_wallets(id) on delete cascade,
  tx_hash text not null,
  chain_id integer not null default 196 check (chain_id = 196),
  status text not null check (status in ('received', 'not_for_wallet', 'failed', 'not_found', 'unsupported_asset')),
  asset_symbol text check (asset_symbol in ('USDT0', 'USDT', 'OKB')),
  amount numeric(38, 18),
  amount_label text,
  token_address text,
  explorer_url text,
  raw_json jsonb not null default '{}'::jsonb,
  verified_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists hwallet_wallet_transfers_user_tx_hash_idx
  on hwallet_wallet_transfers(user_id, lower(tx_hash));
create index if not exists hwallet_wallet_transfers_wallet_created_idx
  on hwallet_wallet_transfers(wallet_id, created_at desc);

create table if not exists hwallet_agent_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references app_users(id) on delete cascade,
  title text not null default 'Agent 会话',
  status text not null default 'active' check (status in ('active', 'archived')),
  last_goal_type text,
  last_orchestration jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists hwallet_agent_sessions_user_updated_idx
  on hwallet_agent_sessions(user_id, updated_at desc);

create table if not exists hwallet_agent_messages (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references hwallet_agent_sessions(id) on delete cascade,
  user_id text not null references app_users(id) on delete cascade,
  role text not null check (role in ('user', 'agent', 'tool')),
  kind text not null default 'text' check (kind in ('text', 'progress', 'card')),
  content text,
  card_json jsonb,
  actions_json jsonb not null default '[]'::jsonb,
  orchestration_json jsonb,
  created_at timestamptz not null default now()
);

create index if not exists hwallet_agent_messages_session_created_idx
  on hwallet_agent_messages(session_id, created_at asc);
create index if not exists hwallet_agent_messages_user_created_idx
  on hwallet_agent_messages(user_id, created_at desc);

create table if not exists hwallet_agent_memory_items (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references app_users(id) on delete cascade,
  session_id uuid references hwallet_agent_sessions(id) on delete set null,
  memory_type text not null check (memory_type in ('preference', 'wallet_note', 'strategy_hint', 'knowledge_note', 'conversation_summary')),
  content text not null,
  content_json jsonb not null default '{}'::jsonb,
  source text not null default 'agent_session',
  embedding_ref text,
  created_at timestamptz not null default now()
);

create index if not exists hwallet_agent_memory_user_type_created_idx
  on hwallet_agent_memory_items(user_id, memory_type, created_at desc);

create table if not exists hwallet_agent_records (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references app_users(id) on delete cascade,
  session_id uuid references hwallet_agent_sessions(id) on delete set null,
  idempotency_key text,
  type text not null check (type in ('prediction.saved', 'tracking.saved', 'strategy.saved', 'simulation.saved')),
  title text not null,
  note text not null default '',
  card_json jsonb not null,
  created_at timestamptz not null default now()
);

create unique index if not exists hwallet_agent_records_user_idempotency_idx
  on hwallet_agent_records(user_id, idempotency_key)
  where idempotency_key is not null;
create index if not exists hwallet_agent_records_user_type_created_idx
  on hwallet_agent_records(user_id, type, created_at desc);

create table if not exists hwallet_agent_runs (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references app_users(id) on delete cascade,
  session_id uuid references hwallet_agent_sessions(id) on delete set null,
  intent text not null,
  status text not null check (status in ('completed', 'blocked', 'failed', 'running')),
  input_json jsonb not null default '{}'::jsonb,
  output_json jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create index if not exists hwallet_agent_runs_user_started_idx
  on hwallet_agent_runs(user_id, started_at desc);

create table if not exists hwallet_agent_actions (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references app_users(id) on delete cascade,
  session_id uuid references hwallet_agent_sessions(id) on delete set null,
  run_id uuid references hwallet_agent_runs(id) on delete set null,
  action text not null,
  status text not null check (status in ('allowed', 'blocked', 'completed', 'failed')),
  capability_json jsonb not null default '{}'::jsonb,
  policy_result_json jsonb not null default '{}'::jsonb,
  idempotency_key text,
  money_moved boolean not null default false,
  created_at timestamptz not null default now()
);

create unique index if not exists hwallet_agent_actions_user_idempotency_idx
  on hwallet_agent_actions(user_id, idempotency_key)
  where idempotency_key is not null;
create index if not exists hwallet_agent_actions_user_created_idx
  on hwallet_agent_actions(user_id, created_at desc);

create table if not exists hwallet_audit_events (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references app_users(id) on delete cascade,
  session_id uuid references hwallet_agent_sessions(id) on delete set null,
  record_id uuid references hwallet_agent_records(id) on delete set null,
  wallet_transfer_id uuid references hwallet_wallet_transfers(id) on delete set null,
  action_id uuid references hwallet_agent_actions(id) on delete set null,
  type text not null,
  title text not null,
  note text not null default '',
  status text not null check (status in ('success', 'blocked', 'info')),
  money_moved boolean not null default false,
  market_id text,
  market_title text,
  tx_hash text,
  explorer_url text,
  chain_id integer,
  asset_symbol text,
  amount_label text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists hwallet_audit_events_user_created_idx
  on hwallet_audit_events(user_id, created_at desc);
create index if not exists hwallet_audit_events_user_type_created_idx
  on hwallet_audit_events(user_id, type, created_at desc);

create table if not exists hwallet_market_snapshots (
  id uuid primary key default gen_random_uuid(),
  provider text not null check (provider in ('okx-outcomes', 'polymarket-plugin', 'local-sample')),
  chain_id integer check (chain_id in (137, 196)),
  event_id text,
  market_id text not null,
  question text not null,
  status text,
  market_type text,
  yes_asset_id text,
  no_asset_id text,
  yes_price numeric(18, 8),
  no_price numeric(18, 8),
  liquidity numeric(38, 18),
  volume_24h numeric(38, 18),
  volume numeric(38, 18),
  start_time timestamptz,
  end_date timestamptz,
  raw_json jsonb not null default '{}'::jsonb,
  captured_at timestamptz not null default now()
);

create index if not exists hwallet_market_snapshots_provider_market_captured_idx
  on hwallet_market_snapshots(provider, market_id, captured_at desc);
create index if not exists hwallet_market_snapshots_captured_idx
  on hwallet_market_snapshots(captured_at desc);

create table if not exists hwallet_tee_signers (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references app_users(id) on delete cascade,
  wallet_id uuid references hwallet_wallets(id) on delete set null,
  signer_ref text not null,
  signer_type text not null default 'tee' check (signer_type in ('tee')),
  public_address text,
  export_allowed boolean not null default false check (export_allowed = false),
  status text not null default 'planned' check (status in ('planned', 'active', 'revoked')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists hwallet_tee_signers_user_ref_idx
  on hwallet_tee_signers(user_id, signer_ref);

-- Supabase safety boundary.
-- The App writes through trusted backend/database connections, not public anon table access.
-- Enabling RLS by default keeps newly created public tables from becoming readable/writable
-- through Supabase client keys until explicit policies are designed.
alter table app_users enable row level security;
alter table agents enable row level security;
alter table agent_vaults enable row level security;
alter table agent_policies enable row level security;
alter table agent_memories enable row level security;
alter table agent_messages enable row level security;
alter table agent_runs enable row level security;
alter table trade_intents enable row level security;
alter table execution_previews enable row level security;
alter table execution_records enable row level security;
alter table audit_events enable row level security;
alter table training_exports enable row level security;
alter table hwallet_wallets enable row level security;
alter table hwallet_wallet_assets enable row level security;
alter table hwallet_wallet_transfers enable row level security;
alter table hwallet_agent_sessions enable row level security;
alter table hwallet_agent_messages enable row level security;
alter table hwallet_agent_memory_items enable row level security;
alter table hwallet_agent_records enable row level security;
alter table hwallet_agent_runs enable row level security;
alter table hwallet_agent_actions enable row level security;
alter table hwallet_audit_events enable row level security;
alter table hwallet_market_snapshots enable row level security;
alter table hwallet_tee_signers enable row level security;
