-- Agent Wallet production schema draft.
-- Target database: Postgres 15+.
-- UUIDs are generated by the app today; production can switch to gen_random_uuid().

create table if not exists app_users (
  id text primary key,
  privy_user_id text unique,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists agents (
  id uuid primary key,
  owner_user_id text not null references app_users(id),
  name text not null,
  status text not null check (status in ('active', 'paused', 'revoked')),
  strategy_profile text not null,
  execution_mode text not null check (execution_mode in ('observe_only', 'simulate', 'mainnet_small')),
  user_wallet_address text,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists agent_vaults (
  agent_id uuid primary key references agents(id) on delete cascade,
  chain_id integer not null default 196,
  chain_name text not null default 'X Layer',
  address text not null,
  display_address text not null,
  wallet_type text not null,
  balance_snapshot_okb numeric(38, 18) not null default 0,
  last_balance_sync_at timestamptz not null
);

create table if not exists agent_policies (
  agent_id uuid primary key references agents(id) on delete cascade,
  max_single_spend_okb numeric(38, 18) not null,
  daily_budget_okb numeric(38, 18) not null,
  daily_loss_limit_okb numeric(38, 18) not null,
  allowed_markets text[] not null,
  allowed_tokens text[] not null,
  expires_at timestamptz not null,
  revoked boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists agent_memories (
  agent_id uuid primary key references agents(id) on delete cascade,
  user_preferences jsonb not null default '[]'::jsonb,
  risk_profile jsonb not null default '{}'::jsonb,
  strategy_hints jsonb not null default '[]'::jsonb,
  recent_lessons jsonb not null default '[]'::jsonb,
  counters jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null
);

create table if not exists agent_messages (
  id uuid primary key,
  agent_id uuid not null references agents(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'tool')),
  content text not null,
  action text,
  decision jsonb,
  tool_result jsonb,
  created_at timestamptz not null
);

create index if not exists agent_messages_agent_created_idx on agent_messages(agent_id, created_at desc);

create table if not exists agent_runs (
  id uuid primary key,
  agent_id uuid not null references agents(id) on delete cascade,
  status text not null check (status in ('completed', 'blocked', 'failed')),
  goal text not null,
  router jsonb not null,
  observed_market_count integer not null,
  selected_market_id text,
  selected_question text,
  selection_reason text not null,
  intent_id uuid,
  preview_id uuid,
  risk_notes jsonb not null default '[]'::jsonb,
  created_at timestamptz not null
);

create index if not exists agent_runs_agent_created_idx on agent_runs(agent_id, created_at desc);

create table if not exists trade_intents (
  id uuid primary key,
  agent_id uuid not null references agents(id) on delete cascade,
  market text not null,
  market_source text not null,
  side text not null,
  amount_okb numeric(38, 18) not null,
  confidence numeric(8, 6) not null,
  expected_probability numeric(8, 6) not null,
  market_probability numeric(8, 6),
  external_market_id text,
  external_market_slug text,
  external_question text,
  plugin_name text,
  tool_route jsonb,
  execution_plan jsonb,
  live_mode_required boolean,
  preview_required boolean,
  reasoning text not null,
  status text not null,
  risk_notes jsonb not null default '[]'::jsonb,
  created_at timestamptz not null
);

create index if not exists trade_intents_agent_created_idx on trade_intents(agent_id, created_at desc);

create table if not exists execution_previews (
  id uuid primary key,
  agent_id uuid not null references agents(id) on delete cascade,
  intent_id uuid not null references trade_intents(id) on delete cascade,
  provider text not null,
  mode text not null check (mode in ('paper', 'live')),
  market text not null,
  side text not null,
  amount_okb numeric(38, 18) not null,
  estimated_cost_okb numeric(38, 18) not null,
  estimated_gas_okb numeric(38, 18) not null,
  price numeric(8, 6),
  tool_route jsonb,
  warnings jsonb not null default '[]'::jsonb,
  safety_summary jsonb not null default '{}'::jsonb,
  confirmation_text text,
  confirmation_code text,
  confirmation_status text not null,
  confirmation_attempts integer not null default 0,
  max_confirmation_attempts integer not null default 5,
  confirmed_at timestamptz,
  confirmed_by text,
  expires_at timestamptz not null,
  created_at timestamptz not null
);

create index if not exists execution_previews_agent_created_idx on execution_previews(agent_id, created_at desc);
create index if not exists execution_previews_intent_fresh_idx on execution_previews(intent_id, expires_at desc);

create table if not exists execution_records (
  id uuid primary key,
  agent_id uuid not null references agents(id) on delete cascade,
  intent_id uuid not null references trade_intents(id) on delete cascade,
  status text not null check (status in ('simulated', 'executed', 'blocked', 'failed')),
  tx_hash text,
  cost_okb numeric(38, 18) not null default 0,
  error text,
  explorer_url text,
  provider text,
  created_at timestamptz not null
);

create index if not exists execution_records_agent_created_idx on execution_records(agent_id, created_at desc);

create table if not exists audit_events (
  id uuid primary key,
  agent_id uuid not null references agents(id) on delete cascade,
  type text not null,
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null
);

create index if not exists audit_events_agent_created_idx on audit_events(agent_id, created_at desc);

create table if not exists training_exports (
  id uuid primary key,
  agent_id uuid references agents(id) on delete set null,
  storage_url text not null,
  format text not null default 'jsonl',
  example_count integer not null,
  created_at timestamptz not null default now()
);
